apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "whisper"}}}'
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: whisper
    networking.gke.io/managed-certificates: managed-cert
  labels:
    app.kubernetes.io/name: whisper-api
  name: whisper-whisper-api
spec:
  rules:
  - host: whisper.sandbox.eng.zencore.dev
    http:
      paths:
      - backend:
          service:
            name: whisper-whisper-api
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - whisper.sandbox.eng.zencore.dev
    secretName: whisper-sandbox-tls
