apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app.kubernetes.io/name: whisper-api
  name: whisper-whisper-api
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: whisper
    app.kubernetes.io/name: whisper-api
  sessionAffinity: None
  type: ClusterIP
