ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: whisper
    networking.gke.io/managed-certificates: managed-cert
  hosts:
    - host: whisper.sandbox.eng.zencore.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: whisper-sandbox-tls
      hosts:
        - whisper.sandbox.eng.zencore.dev
nodeSelector:
  cloud.google.com/gke-accelerator: nvidia-tesla-t4
resources:
  limits:
    nvidia.com/gpu: 1
